.TH NAENAE 1
.SH NAME
naenae \- the companion to \fBWIP\fR
.SH SYNOPSIS
.B naenae
.SH DESCRIPTION
.B naenae
squashes commits made by \fBWIP\fR. \fBNAENAE\fR searches through recent commits
until the last commit with a message of exactly "WIP" is found. It then
soft-resets to that point and initiates the users preferred commit message
editor. Please refer to the manual for \fBNAENAE\fR for more information.
